### ISSUE TITLE
p method fails test

### ISSUE THREAD

**Issue by levimllr** [learn-co-curriculum/programming-univbasics-3-methods-default-values-lab#9]
```ruby
def meal_choice(food1, food2, meat = "meat")
  puts "What a nutritious meal!"
  p "A plate of #{meat} with #{food1} and #{food2}."
end
```

The code above fails rspec tests, even though it puts "What a nutritious meal!" and the order to the console and return the order. In `meal_choice_spec.rb`,

```ruby
  it 'should puts "What a nutritious meal!" and your order to the console' do
    expect($stdout).to receive(:puts).with("What a nutritious meal!")
    expect($stdout).to receive(:puts).with("A plate of meat with broccoli and macaroni.")
    meal_choice("broccoli", "macaroni")
  end
```

It seems rspec is expected only the `puts` method and not allowing for `p`.

I bring this issue up because the Programming As a Conversion series of readmes teaches the `p` method in addition to `puts` and `print`.

**Comment by sgharms** [comment]
We'll rein things in by suggesting `puts`. Thanks.
